### ISSUE TITLE
SVG export not working

### ISSUE THREAD

**Issue by archnila** [FOSStriangulator/FOSStriangulator#31] opened 2024-03-17 07:13 UTC
For some reason, the svg export isn't working. The file dialog would open but no svg file is saved. However, if I were to save as pdf, it works fine.

**Comment by 12people** [comment] 2024-03-29 18:44
Closing as duplicate of https://github.com/FOSStriangulator/FOSStriangulator/issues/12

Unfortunately, haven't found the time for this yet. Feel free to look into it if you know some Java. :)

**Closed as completed by 12people** 2024-03-29 18:44 UTC
